export const GET_REQUEST="GET_REQUEST";
export const GET_ERROR="GET_ERROR";
export const GET_SUCCESS="GET_SUCCESS";

export const POST_REQUEST="POST_REQUEST";
export const POST_ERROR="POST_ERROR";
export const POST_SUCCESS="POST_SUCCESS";

export const UPDATE_REQUEST="UPDATE_REQUEST";
export const UPDATE_ERROR="UPDATE_ERROR";
export const UPDATE_SUCCESS="UPDATE_SUCCESS";

export const SEARCH_REQUEST="SEARCH_REQUEST";
export const SEARCH_ERROR="SEARCH_ERROR";
export const SEARCH_SUCCESS="SEARCH_SUCCESS";

export const DELETE_REQUEST="DELETE_REQUEST";
export const DELETE_ERROR="DELETE_ERROR";
export const DELETE_SUCCESS="DELETE_SUCCESS";